:Author: soviet_scar
:Email: sro18rs@gmail.com
:Date: 05/06/2018
:Revision: version#
:License: Public Domain

= Project: Simulated Bomb Device

***DISCLAIMER: THIS IS NOT AN ACTUAL BOMB. NOT MEANT TO BE PLACED IN AN ACTUAL BOMB. THIS CODE IS MEANT TO BE USED IN A SIMULATED BOMB FOR USE IN AIRSOFT, PAINTBALL AND, TRAINING SITUATIONS.***

Fake bomb to be used in objective based games or training.

== Step 1: Installation

Assemble the circuit as in the circuit diagram.

== Step 2: Assemble the circuit

Assemble the circuit following the diagram sketch.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board. Also found at https://create.arduino.cc/editor/soviet_scar/1e99c08a-086b-41f8-aabd-5bab95f62c66/preview[Arduino Create: Sim Box Main]

=== Folder structure

....
 Sim_box            => Arduino sketch folder
  ├── Sim_box_main.ino       => main Arduino file
  ├── sketch.png             => an image of the wiring schematics
  └── ReadMe.adoc            => this file
....

=== License
This project is released under a GNU Affero General Public License v3.0 License.

=== Contributing
To contribute to this project please contact Sean Ohmann <sro18rs@gmail.com>. Or, just make some changes and upload to the internet as in the License

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name                       | Quantity
| R1 | 220 Ω Resistor                  | 1      
| P1 | 250 kΩ Potenetiometer           | 1        
| A1 | Arduino Uno R3                  | 1        
| L1 | 16x2 LCD Character Display      | 1
| B1 | Momentary Switch                | 1
| B2 | Single Pole Single Throw Switch | 1    
| L1 | Lock Switch                     | 1    *OPTIONAL*
| X1 | Powerboost 1000 Charger         | 1    
| X2 | Lithium ION Batery Pack 3.7V    | 1    
| E1 | Aluminum Project Box            | 1    
| W1 | ***LOTS*** of assorted wiring   | ∞   
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
