:Author: soviet_scar
:Email: sro18rs@gmail.com
:Date: 05/06/2018
:Revision: version#
:License: Public Domain

= Project: Simulated Bomb Device

Describe your project

== Step 1: Installation


== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Sim_box            => Arduino sketch folder
  ├── Sim_box_main.ino       => main Arduino file
  ├── sketch.json            => an image of the required schematics
  └── ReadMe.adoc            => this file
....

=== License
This project is released under a GNU Affero General Public License v3.0 License.

=== Contributing
To contribute to this project please contact Sean Ohmann <sro18rs@gmail.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
